const express=require('express');
const path=require('path');
const crypto=require('crypto');
const {Pool}=require('pg');

const app=express();
const PORT=process.env.PORT||10000;
const ROOT=__dirname;
const DATABASE_URL=process.env.DATABASE_URL;
if(!DATABASE_URL) throw new Error('DATABASE_URL is required. Create/connect a PostgreSQL database and set DATABASE_URL.');
const pool=new Pool({connectionString:DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false,max:10,idleTimeoutMillis:30000});
const solutions=require('./data/solutions.json');
const now=()=>new Date().toISOString();
const norm=s=>(s||'').toLowerCase();
function hash(p,s=crypto.randomBytes(16).toString('hex')){return s+':'+crypto.scryptSync(p,s,64).toString('hex')}
function verify(p,h){try{const [s,k]=h.split(':');return crypto.timingSafeEqual(Buffer.from(k,'hex'),crypto.scryptSync(p,s,64))}catch{return false}}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{let i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}))}
async function q(text,params=[]){return pool.query(text,params)}

async function initDb(){
 await q(`CREATE TABLE IF NOT EXISTS admins(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,admin_id BIGINT REFERENCES admins(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL);
 CREATE TABLE IF NOT EXISTS demo_requests(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,organisation TEXT NOT NULL,email TEXT NOT NULL,phone TEXT DEFAULT '',country TEXT DEFAULT '',solution TEXT DEFAULT '',industry TEXT DEFAULT '',size TEXT DEFAULT '',problem TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'new',notes TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS assistant_logs(id BIGSERIAL PRIMARY KEY,question TEXT NOT NULL,answer TEXT NOT NULL,source TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS advisor_logs(id BIGSERIAL PRIMARY KEY,problem TEXT NOT NULL,solution TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);`);
 const c=await q('SELECT COUNT(*)::int n FROM admins');
 if(c.rows[0].n===0){const email=process.env.ADMIN_EMAIL||'admin@revoltx.local',pass=process.env.ADMIN_PASSWORD||'ChangeMe123!';await q('INSERT INTO admins(name,email,password_hash) VALUES($1,$2,$3)',['Administrator',email,hash(pass)]);console.log('Admin created:',email,process.env.ADMIN_PASSWORD?'(password from environment)':'temporary password ChangeMe123! - CHANGE IT');}
 await q('DELETE FROM sessions WHERE expires_at <= NOW()');
}

app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:false}));app.use(express.static(path.join(ROOT,'public')));
async function auth(req,res,next){try{const t=cookies(req).rx_admin;if(!t)return res.status(401).json({error:'Unauthorized'});const r=await q(`SELECT a.id,a.name,a.email FROM sessions s JOIN admins a ON a.id=s.admin_id WHERE s.token=$1 AND s.expires_at>NOW()`,[t]);if(!r.rows[0])return res.status(401).json({error:'Session expired'});req.admin=r.rows[0];next()}catch(e){next(e)}}
const ASSISTANT_CONTEXT=`Revolt-X Technologies designs and delivers intelligent, connected technology around how organisations need to work. Revolt-X OS is a connected technology foundation for people, processes, applications, data, permissions, workflows, notifications and integrations. Revolt-X AI supports practical use cases such as AI agents, organisational knowledge, document intelligence, analysis, recommendations and controlled workflow assistance. Revolt-X solution areas include business intelligence and analytics, custom business applications, AI business solutions and agents, CRM and sales intelligence, smart inventory and procurement, fleet and logistics intelligence, property and facility technology, HR and workforce management, workflow and process automation, enterprise AI and data platforms, digital platforms and customer experiences, web/mobile experience technology, IoT and connected operations, systems integration and cloud technology, and technology modernisation. Technology services include custom software development, web application development, mobile app development, UI/UX and product design, AI development, data and analytics engineering, API integration, cloud deployment, software modernisation, support and maintenance. The public website does not advertise AutoLink, Revolt Fleet, Revolt Property or Revolt Intelligence as products. Projects should start from the organisation's problem, desired outcome, users, workflow, data, integrations and operating environment. The company tagline is Ideas Today. A Brighter Tomorrow.`;
function tokens(v){const stop=new Set('what which where when why how does do can could would should about tell explain need want have with from your our this that into they them then than business company solution solutions system systems software please'.split(' '));return [...new Set(norm(v).split(/[^a-z0-9]+/).filter(w=>w.length>2&&!stop.has(w)))]}
function localAssistant(question){const t=norm(question),qt=tokens(question);
 if(/(hello|hi|hey|good morning|good afternoon|good evening)\b/.test(t))return {answer:'Hello. I’m Adriana, the Revolt-X AI Agent. Tell me what you want technology to improve, automate, connect or build and I can guide you to a relevant capability.',source:'Revolt-X'};
 if(/revolt.?x os|\bos\b/.test(t))return {answer:'Revolt-X OS is our connected technology foundation. It is designed to bring people, processes, applications, data, permissions, workflows, notifications and integrations into a more connected operating environment.',source:'Revolt-X OS'};
 if(/revolt.?x ai|artificial intelligence|ai agent/.test(t))return {answer:'Revolt-X AI is our intelligence capability for practical business work, including AI agents, organisational knowledge, document intelligence, analysis, recommendations and controlled workflow assistance.',source:'Revolt-X AI'};
 if(/website|web app|mobile app|software development|ui|ux|api|cloud|moderni/.test(t))return {answer:'Revolt-X provides technology engineering services including custom software, web and mobile applications, UI/UX, AI development, data engineering, API integration, cloud deployment, modernisation, support and maintenance. These are part of a broader capability to build connected technology around the business need.',source:'Revolt-X technology services'};
 if(/price|cost|pricing|quote/.test(t))return {answer:'Scope can vary by users, workflows, integrations, data, infrastructure and support. Start a Project or Request a Demo and describe the requirement so Revolt-X can scope an appropriate approach.',source:'Revolt-X commercial guidance'};
 if(/demo|meeting|consult|contact|talk|speak|project/.test(t))return {answer:'Use Start a Project if you have a business challenge, idea or transformation need. You do not need a technical specification. Request a Demo is also available when you want to explore a specific Revolt-X capability.',source:'Revolt-X'};
 if(/what.*(build|offer|do)|services|solutions/.test(t))return {answer:'Revolt-X designs intelligent, connected technology across 15 solution areas, including business systems, AI, automation, data, digital platforms, web and mobile experiences, IoT, cloud and integration, and technology modernisation. Revolt-X OS and Revolt-X AI are the two signature technology pillars.',source:'Revolt-X solutions'};
 const ranked=solutions.map(x=>{const hay=tokens([x.title,x.summary,...x.features,...x.useCases].join(' '));const overlap=qt.filter(w=>hay.includes(w)).length;return {x,score:overlap}}).sort((a,b)=>b.score-a.score);
 if(ranked[0]?.score>=2){const x=ranked[0].x;return {answer:`${x.title} could be a relevant starting point. ${x.summary} A tailored approach would be scoped around your users, workflow, data, integrations and operating environment.`,source:`Revolt-X: ${x.title}`};}
 return null;
}
async function aiAssistant(question){const key=process.env.OPENAI_API_KEY;if(!key)return null;const model=process.env.OPENAI_MODEL||'gpt-5.6-luna';
 try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${key}`},body:JSON.stringify({model,instructions:`You are Adriana, the Revolt-X AI Agent on the Revolt-X Technologies website. Be accurate, concise and commercially useful. Never invent Revolt-X products, clients, prices, capabilities or claims. Use this verified company context when relevant: ${ASSISTANT_CONTEXT} If a question is unrelated to Revolt-X, you may answer general factual questions, but clearly distinguish general information from Revolt-X information. If uncertain, say so.`,input:question,max_output_tokens:500})});if(!r.ok){console.error('AI assistant HTTP',r.status,await r.text());return null}const j=await r.json();const text=j.output_text||j.output?.flatMap(o=>o.content||[]).map(c=>c.text).filter(Boolean).join('\n');return text?{answer:text,source:'Adriana · Revolt-X AI'}:null}catch(e){console.error('AI assistant failed',e);return null}}
app.post('/api/assistant',async(req,res,next)=>{try{const question=(req.body.question||'').trim();if(!question)return res.status(400).json({answer:'Please enter a question.'});let result=localAssistant(question);if(!result)result=await aiAssistant(question);if(!result)result={answer:'I do not have enough verified information to answer that accurately. I can help with Revolt-X products and solutions, or you can describe the business problem you want to solve. For broad general questions, connect an AI provider to Ask Revolt-X so I can answer beyond the verified Revolt-X knowledge base.',source:'Revolt-X verified knowledge'};await q('INSERT INTO assistant_logs(question,answer,source) VALUES($1,$2,$3)',[question,result.answer,result.source]);res.json(result)}catch(e){next(e)}});
app.post('/api/advisor',async(req,res,next)=>{try{const p=(req.body.problem||'').trim(),t=norm(p),rules=[['inventory-procurement',['stock','inventory','warehouse','supplier','procurement','reorder']],['fleet-logistics',['vehicle','fleet','driver','gps','delivery','route','fuel']],['crm-sales',['customer','lead','sales','crm','pipeline']],['hr-workforce',['staff','employee','payroll','leave','attendance','hr']],['property-facility',['property','rent','airbnb','tenant','facility']],['business-intelligence',['excel','data','dashboard','report','forecast','analytics']],['enterprise-data',['document','contract','policy','knowledge','manual']],['workflow-automation',['approval','manual','workflow','form','process']]];let best={slug:'custom-applications',score:0};for(const [slug,keys] of rules){const score=keys.filter(k=>t.includes(k)).length;if(score>best.score)best={slug,score}}const s=solutions.find(x=>x.slug===best.slug)||solutions[1];await q('INSERT INTO advisor_logs(problem,solution) VALUES($1,$2)',[p,s.title]);res.json({solution:s.title,reason:s.summary,capabilities:s.features.slice(0,5)})}catch(e){next(e)}});
app.post('/api/demo',async(req,res,next)=>{try{const d=req.body||{};if(!d.name||!d.email||!d.organisation||!d.problem)return res.status(400).json({ok:false,message:'Please complete the required fields.'});await q(`INSERT INTO demo_requests(name,organisation,email,phone,country,solution,industry,size,problem) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[d.name,d.organisation,d.email,d.phone||'',d.country||'',d.solution||'',d.industry||'',d.size||'',d.problem]);res.json({ok:true,message:'Demo request received. Thank you.'})}catch(e){next(e)}});
app.post('/api/admin/login',async(req,res,next)=>{try{const {email,password}=req.body,r=await q('SELECT * FROM admins WHERE lower(email)=lower($1)',[email||'']),row=r.rows[0];if(!row||!verify(password||'',row.password_hash))return res.status(401).json({ok:false,message:'Invalid email or password.'});const token=crypto.randomBytes(32).toString('hex'),exp=new Date(Date.now()+8*3600000);await q('INSERT INTO sessions(token,admin_id,expires_at) VALUES($1,$2,$3)',[token,row.id,exp]);res.setHeader('Set-Cookie',`rx_admin=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${process.env.NODE_ENV==='production'?'; Secure':''}`);res.json({ok:true})}catch(e){next(e)}});
app.post('/api/admin/logout',auth,async(req,res,next)=>{try{const t=cookies(req).rx_admin;await q('DELETE FROM sessions WHERE token=$1',[t]);res.setHeader('Set-Cookie','rx_admin=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');res.json({ok:true})}catch(e){next(e)}});
app.get('/api/admin/me',auth,(req,res)=>res.json(req.admin));
app.get('/api/admin/dashboard',auth,async(req,res,next)=>{try{const [total,newN,assistant,advisor,recent]=await Promise.all([q('SELECT COUNT(*)::int n FROM demo_requests'),q("SELECT COUNT(*)::int n FROM demo_requests WHERE status='new'"),q('SELECT COUNT(*)::int n FROM assistant_logs'),q('SELECT COUNT(*)::int n FROM advisor_logs'),q('SELECT * FROM demo_requests ORDER BY id DESC LIMIT 6')]);res.json({stats:{total:total.rows[0].n,new:newN.rows[0].n,assistant:assistant.rows[0].n,advisor:advisor.rows[0].n},recent:recent.rows})}catch(e){next(e)}});
app.get('/api/admin/demos',auth,async(req,res,next)=>{try{res.json((await q('SELECT * FROM demo_requests ORDER BY id DESC')).rows)}catch(e){next(e)}});
app.patch('/api/admin/demos/:id',auth,async(req,res,next)=>{try{const {status,notes}=req.body;if(!['new','contacted','qualified','scheduled','closed'].includes(status))return res.status(400).json({error:'Invalid status'});await q('UPDATE demo_requests SET status=$1,notes=$2 WHERE id=$3',[status,notes||'',req.params.id]);res.json({ok:true})}catch(e){next(e)}});
app.delete('/api/admin/demos/:id',auth,async(req,res,next)=>{try{await q('DELETE FROM demo_requests WHERE id=$1',[req.params.id]);res.json({ok:true})}catch(e){next(e)}});
app.get('/api/admin/assistant',auth,async(req,res,next)=>{try{res.json((await q('SELECT * FROM assistant_logs ORDER BY id DESC LIMIT 200')).rows)}catch(e){next(e)}});
app.get('/api/admin/advisor',auth,async(req,res,next)=>{try{res.json((await q('SELECT * FROM advisor_logs ORDER BY id DESC LIMIT 200')).rows)}catch(e){next(e)}});
app.post('/api/admin/password',auth,async(req,res,next)=>{try{const {currentPassword,newPassword}=req.body,row=(await q('SELECT * FROM admins WHERE id=$1',[req.admin.id])).rows[0];if(!verify(currentPassword||'',row.password_hash))return res.status(400).json({message:'Current password is incorrect.'});if((newPassword||'').length<10)return res.status(400).json({message:'Use at least 10 characters.'});await q('UPDATE admins SET password_hash=$1 WHERE id=$2',[hash(newPassword),req.admin.id]);res.json({ok:true,message:'Password changed.'})}catch(e){next(e)}});
app.get('/api/health',async(req,res)=>{try{await q('SELECT 1');res.json({ok:true,service:'Revolt-X website',database:'postgresql'})}catch{res.status(503).json({ok:false,database:'unavailable'})}});
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Server error. Please try again.'})});
initDb().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log('Revolt-X running on port '+PORT))).catch(e=>{console.error('Database initialization failed:',e);process.exit(1)});
