const express=require('express');
const path=require('path');
const crypto=require('crypto');
const {Pool}=require('pg');

const app=express();
const PORT=process.env.PORT||10000;
const ROOT=__dirname;
const DATABASE_URL=process.env.DATABASE_URL;
if(!DATABASE_URL) throw new Error('DATABASE_URL is required. Create/connect a PostgreSQL database and set DATABASE_URL.');
const pool=new Pool({connectionString:DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false,max:10,idleTimeoutMillis:30000});
const solutions=require('./data/solutions.json');
const now=()=>new Date().toISOString();
const norm=s=>(s||'').toLowerCase();
function hash(p,s=crypto.randomBytes(16).toString('hex')){return s+':'+crypto.scryptSync(p,s,64).toString('hex')}
function verify(p,h){try{const [s,k]=h.split(':');return crypto.timingSafeEqual(Buffer.from(k,'hex'),crypto.scryptSync(p,s,64))}catch{return false}}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{let i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}))}
async function q(text,params=[]){return pool.query(text,params)}

async function initDb(){
 await q(`CREATE TABLE IF NOT EXISTS admins(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,admin_id BIGINT REFERENCES admins(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL);
 CREATE TABLE IF NOT EXISTS demo_requests(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,organisation TEXT NOT NULL,email TEXT NOT NULL,phone TEXT DEFAULT '',country TEXT DEFAULT '',solution TEXT DEFAULT '',industry TEXT DEFAULT '',size TEXT DEFAULT '',problem TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'new',notes TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS assistant_logs(id BIGSERIAL PRIMARY KEY,question TEXT NOT NULL,answer TEXT NOT NULL,source TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS advisor_logs(id BIGSERIAL PRIMARY KEY,problem TEXT NOT NULL,solution TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);`);
 const c=await q('SELECT COUNT(*)::int n FROM admins');
 if(c.rows[0].n===0){const email=process.env.ADMIN_EMAIL||'admin@revoltx.local',pass=process.env.ADMIN_PASSWORD||'ChangeMe123!';await q('INSERT INTO admins(name,email,password_hash) VALUES($1,$2,$3)',['Administrator',email,hash(pass)]);console.log('Admin created:',email,process.env.ADMIN_PASSWORD?'(password from environment)':'temporary password ChangeMe123! - CHANGE IT');}
 await q('DELETE FROM sessions WHERE expires_at <= NOW()');
}

app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:false}));app.use(express.static(path.join(ROOT,'public')));
async function auth(req,res,next){try{const t=cookies(req).rx_admin;if(!t)return res.status(401).json({error:'Unauthorized'});const r=await q(`SELECT a.id,a.name,a.email FROM sessions s JOIN admins a ON a.id=s.admin_id WHERE s.token=$1 AND s.expires_at>NOW()`,[t]);if(!r.rows[0])return res.status(401).json({error:'Session expired'});req.admin=r.rows[0];next()}catch(e){next(e)}}
function siteAnswer(question){const t=norm(question),scores=solutions.map(s=>({s,score:[s.title,s.summary,...s.features,...s.useCases].reduce((n,x)=>n+(t.split(/\W+/).some(w=>w.length>3&&norm(x).includes(w))?1:0),0)})).sort((a,b)=>b.score-a.score);if(/demo|meeting|consult/.test(t))return 'You can request a tailored demo from the Request a Demo page. Tell us your organisation, preferred solution and business problem.';if(/revolt|service|solution|build|software|business/.test(t)||scores[0].score>1){const s=scores[0].s;return `A relevant Revolt-X option is ${s.title}. ${s.summary} Typical capabilities include ${s.features.slice(0,4).join(', ')}. You can open its solution page or request a tailored demo.`}return null}
app.post('/api/assistant',async(req,res,next)=>{try{const question=(req.body.question||'').trim();if(!question)return res.status(400).json({answer:'Please enter a question.'});let answer=siteAnswer(question),source='Revolt-X knowledge base';if(!answer){try{const u='https://en.wikipedia.org/w/api.php?action=query&generator=search&gsrsearch='+encodeURIComponent(question)+'&gsrlimit=1&prop=extracts&exintro=1&explaintext=1&format=json&origin=*';const r=await fetch(u,{headers:{'User-Agent':'RevoltXBusinessAssistant/3.0'}}),j=await r.json(),p=j.query?.pages?Object.values(j.query.pages):[];answer=p[0]?.extract?.slice(0,1200)||'I could not find reliable public information for that question.';source=p[0]?.extract?'Wikipedia':'No external result'}catch{answer='Live public information is temporarily unavailable.';source='System'}await q('INSERT INTO assistant_logs(question,answer,source) VALUES($1,$2,$3)',[question,answer,source]);res.json({answer,source})}catch(e){next(e)}});
app.post('/api/advisor',async(req,res,next)=>{try{const p=(req.body.problem||'').trim(),t=norm(p),rules=[['inventory-procurement',['stock','inventory','warehouse','supplier','procurement','reorder']],['fleet-logistics',['vehicle','fleet','driver','gps','delivery','route','fuel']],['crm-sales',['customer','lead','sales','crm','pipeline']],['hr-workforce',['staff','employee','payroll','leave','attendance','hr']],['property-facility',['property','rent','airbnb','tenant','facility']],['business-intelligence',['excel','data','dashboard','report','forecast','analytics']],['enterprise-data',['document','contract','policy','knowledge','manual']],['workflow-automation',['approval','manual','workflow','form','process']]];let best={slug:'custom-applications',score:0};for(const [slug,keys] of rules){const score=keys.filter(k=>t.includes(k)).length;if(score>best.score)best={slug,score}}const s=solutions.find(x=>x.slug===best.slug)||solutions[1];await q('INSERT INTO advisor_logs(problem,solution) VALUES($1,$2)',[p,s.title]);res.json({solution:s.title,reason:s.summary,capabilities:s.features.slice(0,5)})}catch(e){next(e)}});
app.post('/api/demo',async(req,res,next)=>{try{const d=req.body||{};if(!d.name||!d.email||!d.organisation||!d.problem)return res.status(400).json({ok:false,message:'Please complete the required fields.'});await q(`INSERT INTO demo_requests(name,organisation,email,phone,country,solution,industry,size,problem) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[d.name,d.organisation,d.email,d.phone||'',d.country||'',d.solution||'',d.industry||'',d.size||'',d.problem]);res.json({ok:true,message:'Demo request received. Thank you.'})}catch(e){next(e)}});
app.post('/api/admin/login',async(req,res,next)=>{try{const {email,password}=req.body,r=await q('SELECT * FROM admins WHERE lower(email)=lower($1)',[email||'']),row=r.rows[0];if(!row||!verify(password||'',row.password_hash))return res.status(401).json({ok:false,message:'Invalid email or password.'});const token=crypto.randomBytes(32).toString('hex'),exp=new Date(Date.now()+8*3600000);await q('INSERT INTO sessions(token,admin_id,expires_at) VALUES($1,$2,$3)',[token,row.id,exp]);res.setHeader('Set-Cookie',`rx_admin=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${process.env.NODE_ENV==='production'?'; Secure':''}`);res.json({ok:true})}catch(e){next(e)}});
app.post('/api/admin/logout',auth,async(req,res,next)=>{try{const t=cookies(req).rx_admin;await q('DELETE FROM sessions WHERE token=$1',[t]);res.setHeader('Set-Cookie','rx_admin=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');res.json({ok:true})}catch(e){next(e)}});
app.get('/api/admin/me',auth,(req,res)=>res.json(req.admin));
app.get('/api/admin/dashboard',auth,async(req,res,next)=>{try{const [total,newN,assistant,advisor,recent]=await Promise.all([q('SELECT COUNT(*)::int n FROM demo_requests'),q("SELECT COUNT(*)::int n FROM demo_requests WHERE status='new'"),q('SELECT COUNT(*)::int n FROM assistant_logs'),q('SELECT COUNT(*)::int n FROM advisor_logs'),q('SELECT * FROM demo_requests ORDER BY id DESC LIMIT 6')]);res.json({stats:{total:total.rows[0].n,new:newN.rows[0].n,assistant:assistant.rows[0].n,advisor:advisor.rows[0].n},recent:recent.rows})}catch(e){next(e)}});
app.get('/api/admin/demos',auth,async(req,res,next)=>{try{res.json((await q('SELECT * FROM demo_requests ORDER BY id DESC')).rows)}catch(e){next(e)}});
app.patch('/api/admin/demos/:id',auth,async(req,res,next)=>{try{const {status,notes}=req.body;if(!['new','contacted','qualified','scheduled','closed'].includes(status))return res.status(400).json({error:'Invalid status'});await q('UPDATE demo_requests SET status=$1,notes=$2 WHERE id=$3',[status,notes||'',req.params.id]);res.json({ok:true})}catch(e){next(e)}});
app.delete('/api/admin/demos/:id',auth,async(req,res,next)=>{try{await q('DELETE FROM demo_requests WHERE id=$1',[req.params.id]);res.json({ok:true})}catch(e){next(e)}});
app.get('/api/admin/assistant',auth,async(req,res,next)=>{try{res.json((await q('SELECT * FROM assistant_logs ORDER BY id DESC LIMIT 200')).rows)}catch(e){next(e)}});
app.get('/api/admin/advisor',auth,async(req,res,next)=>{try{res.json((await q('SELECT * FROM advisor_logs ORDER BY id DESC LIMIT 200')).rows)}catch(e){next(e)}});
app.post('/api/admin/password',auth,async(req,res,next)=>{try{const {currentPassword,newPassword}=req.body,row=(await q('SELECT * FROM admins WHERE id=$1',[req.admin.id])).rows[0];if(!verify(currentPassword||'',row.password_hash))return res.status(400).json({message:'Current password is incorrect.'});if((newPassword||'').length<10)return res.status(400).json({message:'Use at least 10 characters.'});await q('UPDATE admins SET password_hash=$1 WHERE id=$2',[hash(newPassword),req.admin.id]);res.json({ok:true,message:'Password changed.'})}catch(e){next(e)}});
app.get('/api/health',async(req,res)=>{try{await q('SELECT 1');res.json({ok:true,service:'Revolt-X website',database:'postgresql'})}catch{res.status(503).json({ok:false,database:'unavailable'})}});
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Server error. Please try again.'})});
initDb().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log('Revolt-X running on port '+PORT))).catch(e=>{console.error('Database initialization failed:',e);process.exit(1)});
